spring.application.name=Auth-service

spring.config.import=configserver:http://localhost:6060

#twilio configs
twilio.account.sid=ACb2482e028e1cb010665c63c0f52b7bf7
twilio.auth.token=7a3b2a8255ef189a61bc864b1d7047e3
twilio.phone.number=+18312284170
isTwilioEnabled=false

jwt.secretKey=ejKV/UXBxT56BucMd/c18r04omta2Z7MX+EDTjExUkk=
jwt.expirationTime=1800000

logging.level.org.springframework.security=DEBUG
