pipeline {
    agent  any

    tools {
        jdk 'JDK21'
    }

    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build & Checkstyle') {
             steps {
             bat 'cd Auth-service && mvn clean verify -Dspring.cloud.config.enabled=false'
             }
        }
        stage('SonarQube Analysis') {
             steps {
             withSonarQubeEnv('SonarQube') {
             bat 'cd Auth-service && mvn sonar:sonar'
             }
             }
        }
        stage('SonarQube Quality') {
            steps {
               timeout(time: 5, unit: 'MINUTES') {
               waitForQualityGate abortPipeline: true
               }
            }
        }
        stage('Package') {
            steps {
               bat 'cd Auth-service && mvn package -DskipTests'
            }
        }
    }

    post {
         success {
             echo 'Auth service pipeline completed successfully !'
         }
         failure {
              echo 'Auth service pipeline failed '
         }
         always {
              echo 'Pipeline execution completed'
         }

    }
}
